### ISSUE TITLE
Update Contact link to redirect to BlueXolo Google Group

### ISSUE THREAD

**Issue by Grixtli** [BlueXolo-Tools/DocumentationWebPage#5]

**Comment by Grixtli** [comment]
@capikp we need more information

**Comment by raaul19** [comment]
![bx2](https://user-images.githubusercontent.com/59990650/75313284-1274d380-5822-11ea-86c7-eff50e085415.png)

I changed the "Contact" button to "Quick Links" that shows the links at the buttom of the page. Adolfo and I talked if the "Contact" button is really required because they are already 2 buttons, at the top right, one for the GitHub contact and the other one is for the Google Group.

**Comment by capikp** [comment]
I think the best solution for this issue is change the name to the button 'Contact' to 'Quick links'. Maybe we can add new button 'Contact' to redirect to BlueXolo Google group, but currently we have a button for this task.

What do you think about this idea? 

![image](https://user-images.githubusercontent.com/46430704/75612343-26515b80-5ae8-11ea-8b57-f10cf7844b65.png)
